### ISSUE TITLE
Gulp integration (gulp-jade2php)

### ISSUE THREAD

**Issue by OnkelTem** [SE7ENSKY/jade2php#13]
When using gulp-jade2php:

```
Error: Cannot find module 'jade2php'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/sites/mclinic/node_modules/gulp-jade2php/index.js:11:14)
    at Object.<anonymous> (/var/www/sites/mclinic/node_modules/gulp-jade2php/index.js:48:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Also, it's not clear what do you mean under "temporary" solution here https://www.npmjs.com/package/gulp-jade2php and why do you suggest using gulp-accord which doesn't support jade2php or it does?

**Comment by OnkelTem** [comment]
Oh, just noticed - there is no index.js, so it doesn't provide anything, right?
No wonder it doesn't work with gulp-jade2php which tries to require() it.
So what was the idea behind gulp-jade2php?

**Comment by ivankravchenko** [comment]
latest version of jade2php must require()-able without problem, please check

**Comment by OnkelTem** [comment]
A moment

**Comment by OnkelTem** [comment]
Ok, got the version from git (latest commit is 98d02c45)
Then I've replaced the contents of `gulp-jade2php/node_modules/jade2php` directory with the version I got.
Still watching error :(

**Comment by ivankravchenko** [comment]
`package.json`:

``` json
{
  "dependencies": {
    "jade2php": "^1.1.7"
  }
}
```

`index.js`:

``` js
var jade2php = require("jade2php");
if (jade2php) {
        console.log("jade2php require() success");
} else {
        console.log("jade2php require() failure");
}
```

```
$ npm install
$ node index.js 
jade2php require() success
```

Not sure what's problem with `gulp-jade2php`.

@FranzSkuffka , could you mind to assist with that?

**Comment by janwirth** [comment]
The gulp-jade2php module is just crap tbh. I am going to unpublish it. I lacked some experience and understanding when i wrote this. 
Creating an adapter for https://github.com/jenius/accord is the way to go imho.

**Comment by OnkelTem** [comment]
> jade2php require() success

странно, так у меня тоже получилось

**Comment by OnkelTem** [comment]
> Creating an adapter for https://github.com/jenius/accord is the way to go imho.

Can't wait!

**Comment by ivankravchenko** [comment]
@OnkelTem, cloned git repo isn't same as fetching NPM module.
Git repo maintain sources (coffee, tests), while NPM module contain compiled output (js, no tests, no coffee).
To make your-way git-cloned repo work as an NPM module, do `npm install ; npm run prepublish` in repo directory.

**Comment by ivankravchenko** [comment]
Does this issue actual yet?

**Comment by janwirth** [comment]
There is a solution available:
https://www.npmjs.com/package/gulp-jade2php
