### ISSUE TITLE
'jade_indent = []' on the top of php file

### ISSUE THREAD

**Issue by OnkelTem** [SE7ENSKY/jade2php#18]
On the top of resulting file I get one extra line:

``` html
var jade_indent = [];
<!DOCTYPE html>
```

I invoke jade2php from gulp using gulp-jade2php

**Comment by ivankravchenko** [comment]
Fixed in jade2php@1.1.8, 2a0993eeb2569e9ba7942b6a6e6e63d03bc79822

**Comment by OnkelTem** [comment]
Nice "fix", so it is now impossible to let jade to set indents (to at least analyze resulting PHP tempaltes).

How do you estimate the difficulty of providing full support of the pretty print?

Or we can't do anything with surprises like?:

``` js
if (this.pp) {
  this.buf.push("var jade_indent = [];");
}
```

**Comment by ivankravchenko** [comment]
Pretty code and pretty output options are not implemented.
Actually, that was not a fix, just a stub.
This is about 3-7 workhours.
But I can't asset priority for `jade2php` next few months.

**Comment by OnkelTem** [comment]
> Pretty code and pretty output options are not implemented.

I'm not arguing, but as I said with this stub we get the output on one line, which is inconvenient when you start developing templates with jade2php.

**Comment by ivankravchenko** [comment]
Issue was resolved, so closing.
Pretty output/code options to be done.
