### ISSUE TITLE
Possible Node 0.12.0 incompatibility

### ISSUE THREAD

**Issue by OnkelTem** [SE7ENSKY/jade2php#20]
_jade2php_ has dev dependency on exec-sync: '^0.1.6', which depends on ffi: '=1.2.5', which is not compatible with Node 0.12.0 (it was [added in 1.2.7](https://github.com/node-ffi/node-ffi/pull/189)). And _exec-sync_ seems to be abandoned.

**Comment by ivankravchenko** [comment]
fixed in 864865e
