### ISSUE TITLE
"npm install" in the project root does not succeed with node 0.12 

### ISSUE THREAD

**Issue by czert** [SE7ENSKY/jade2php#22]
```
Failed at the ffi@1.2.5 install script 'node-gyp rebuild'.
```

I didn't have time to investigate yet, but if anyone encounters this problem, running the command under node 0.10 solves it. You can install node 0.10 through https://github.com/creationix/nvm, for example.

**Comment by ivankravchenko** [comment]
fixed in 864865e

**Comment by czert** [comment]
Nice, thanks!
