### ISSUE TITLE
Ability to turn off <?= and use <?php echo instead

### ISSUE THREAD

**Issue by kevindice** [SE7ENSKY/jade2php#24]
This no longer affects me because PHP (as of 5.4) no longer considers <?= to be a short_tag.  However, I think it would be helpful to have the option.

**Comment by fregante** [comment]
Really this could be a default, there's no advantage in using `<?=` over `<?php echo` in this case.

**Comment by kevindice** [comment]
Agreed.  I had never seen <?= until I looked at the output of this script.
