### ISSUE TITLE
Characters $E2 $96 $A0 in the output

### ISSUE THREAD

**Issue by OnkelTem** [SE7ENSKY/jade2php#30]
This sample code:

``` jade
each field, id in fields
  if field.separator
    != field.separator
  != field.wrapper_prefix
  != field.label_html
  != field.content
  != field.wrapper_suffix
```

results to this php output:

``` php
<?php if ($fields) : foreach ($fields as $id => $field) : $■['id'] = $id;$■['field'] = $field; ?>  <?php if ($field->separator) : ?><?= $field->separator ?><?php endif ?><?= $field->wrapper_prefix ?><?= $field->label_html ?><?= $field->content ?><?= $field->wrapper_suffix ?><?php endforeach; endif ?>
```

where squares represent sequence of characters with codes: `E2 96 A0`

![image](https://sc-cdn.scaleengine.net/i/9fe722b812db48715d23a2c6a8e60047.png)

This doesn't seem to harm my specific template (PHP 5.4.x) but I wonder what are those characters and why?

**Comment by janwirth** [comment]
I think they are temporary variable names for translating the js expressions to php. could be a little more semantic indeed, but who doesn't like some squares in their code? :)
