### ISSUE TITLE
`add()` `attr_class()` & `attr()` are unknown.

### ISSUE THREAD

**Issue by janwirth** [SE7ENSKY/jade2php#32]
Where can I get these functions? are they included in some js library?

**Comment by ivankravchenko** [comment]
It's a runtime.php: https://github.com/SE7ENSKY/jade2php/blob/master/support/runtime.php

**Comment by janwirth** [comment]
So this is a file I have to manually include in my project? Or is there a smarter way to do this?

**Comment by ivankravchenko** [comment]
When you just use jade2php, runtime should be included into resulting file.
If you use `--omit-php-runtime`, then you should include runtime.php manually.

**Comment by janwirth** [comment]
Nice! Thank you.
I want to improve the documentation. Should I extend the readme or the wiki?

**Comment by ivankravchenko** [comment]
I think README is first place to update.
Do we have a wiki? :)

**Comment by janwirth** [comment]
Per default, in the sidebar on the right below pull requests.
