### ISSUE TITLE
no makefile

### ISSUE THREAD

**Issue by janwirth** [SE7ENSKY/jade2php#4]
You have to manually compile the src files. I will ad a makefile.

**Comment by ivankravchenko** [comment]
What do you mean?

**Comment by janwirth** [comment]
something like this:
https://github.com/jenius/accord/blob/master/Makefile
to automate the compilation and distribution process.

**Comment by ivankravchenko** [comment]
Done in 1.1.6 8f11ee4d77530412abc6d18df64d0ba79aea1f75.
