### ISSUE TITLE
doctype xml test is failing.

### ISSUE THREAD

**Issue by janwirth** [SE7ENSKY/jade2php#5]
1) Jade Language Reference Doctype doctype xml:

```
  AssertionError: expected '\nParse error: parse error in /Users/jan/jade2php/__input.php on line 1' to deeply equal '<?xml version="1.0" encoding="utf-8" ?>'
  + expected - actual

  +<?xml version="1.0" encoding="utf-8" ?>
  -
  -Parse error: parse error in /Users/jan/jade2php/__input.php on line 1
```

**Comment by ivankravchenko** [comment]
Do you have PHP installed?
`php --version`

**Comment by ivankravchenko** [comment]
The whole [Jade Language Reference docs.test.coffee](https://github.com/SE7ENSKY/jade2php/blob/master/test/docs.test.coffee) is based on testing that all Jade's original documentation examples compiles with jade2php (and then running with php) exactly same as original Jade compiler.
To test it, PHP executable must be present. I will extend test suite to show if PHP is installed (which is required to run this test).

**Comment by ivankravchenko** [comment]
Done in 60b8932274a90aea5441bcd43377fe01de23675e.
Please let me know if tests are running okay in your environment (of course, PHP installation is required).

**Comment by janwirth** [comment]
109 passing (2s)
all the tests are working with a clone i just did.

PHP 5.5.12-2ubuntu4.1 (cli) (built: Oct 29 2014 11:59:49)
